# @name requisicao
@WebSockets =  "to work with WebSockets in C#"
@historiaBrasil = "A história do Brasil começou com a ocupação dos seres humanos a cerca de 12-20 mil anos. No século XVI, os portugueses começaram a colonizar estas terras e transferiram africanos para serem mão de obra escrava nos engenhos que construíram aqui. Por sua vez, estes trabalhadores forçados trariam novos alimentos e animais que mudariam a história dos povos originários para sempre."

//Iniciar Requisicao
POST http://localhost:5084/api/RequisicoesTAG/IniciarRequisicaoTAG HTTP/1.1
content-Type: application/json

  [
    {
        "Texto" : "c#",
        "perguntas": []
    },
    {
        "Texto" : "websockets"
    }
  ]


//Procurar por tags
###

POST http://localhost:5084/api/RequisicoesTAG/PerguntasPorTags HTTP/1.1
content-Type: application/json

 [
    {
        "Texto" : "Quimica"
    }
  ]
  
###
@id = {{requisicao.response.body.$}}
//Consultar a requisicao pelo id
GET http://localhost:5084/api/Requisicoes/ConsultarRequisicao?id={{id}}

