# @name requisicao

@Tags = "Tags: veterinaria, anamese, cachorro"


POST http://localhost:5084/api/Requisicoes/IniciarRequisicaoTAG?textoEntrada={{Tags}}


###
@id = {{requisicao.response.body.$}}
//Consultar a requisicao pelo id
GET http://localhost:5084/api/Requisicoes/ConsultarRequisicao?id={{id}}

###
//Pesquisa a pergunta pelo id da requisicao

GET http://localhost:5084/api/Requisicoes/ConsultarPergunta?id={{id}}

###
POST http://localhost:5084/api/Requisicoes/ReenviarRequisicao?id={{id}}&textoNormal=false





