###
//Retorna todas as Requisicoes

GET http://localhost:5084/api/Requisicoes/ConsultarRequisicoes

###
//Retorna todos os textos bases
GET http://localhost:5084/api/Requisicoes/ConsultarTextosBases

###
//Retorna todas as perguntas geradas
GET http://172.17.255.255:8002/api/Requisicoes/ConsultarPerguntas

###
GET http://146.190.174.100:8002/api/Requisicoes/ConsultarPerguntas
